<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.8.0 on win32)" generated="20191215 23:33:17.535" rpa="false">
<suite id="s1" name="Tests" source="C:\Users\orest\PycharmProjects\RestApi\tests.robot">
<test id="s1-t1" name="TestsCriteia">
<kw name="CreareCriteria" library="keywords">
<kw name="create criteria">
<arguments>
<arg>${RESOURCE}</arg>
<arg>data_for_criteria</arg>
</arguments>
<assign>
<var>${resonses}</var>
</assign>
<msg timestamp="20191215 23:33:17.876" level="FAIL">No keyword with name 'create criteria' found. Did you mean:
    keywords.Creare Criteria</msg>
<status status="FAIL" starttime="20191215 23:33:17.876" endtime="20191215 23:33:17.876"></status>
</kw>
<status status="FAIL" starttime="20191215 23:33:17.875" endtime="20191215 23:33:17.876"></status>
</kw>
<status status="FAIL" starttime="20191215 23:33:17.873" endtime="20191215 23:33:17.878" critical="yes">No keyword with name 'create criteria' found. Did you mean:
    keywords.Creare Criteria</status>
</test>
<status status="FAIL" starttime="20191215 23:33:17.540" endtime="20191215 23:33:17.879"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Tests">Tests</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20191215 23:33:17.587" level="ERROR">Error in file 'C:\Users\orest\PycharmProjects\RestApi\keywords.robot': Importing test library 'ClientCriteria' failed: ModuleNotFoundError: No module named 'ClientCriteria'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\orest\PycharmProjects\RestApi\venv\Scripts\robot.exe
  C:\Users\orest\AppData\Local\Programs\Python\Python38-32\python38.zip
  C:\Users\orest\AppData\Local\Programs\Python\Python38-32\DLLs
  C:\Users\orest\AppData\Local\Programs\Python\Python38-32\lib
  C:\Users\orest\AppData\Local\Programs\Python\Python38-32
  c:\users\orest\pycharmprojects\restapi\venv
  c:\users\orest\pycharmprojects\restapi\venv\lib\site-packages
  c:\users\orest\pycharmprojects\restapi\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg
  c:\users\orest\pycharmprojects\restapi\venv\lib\site-packages\pip-19.0.3-py3.8.egg</msg>
</errors>
</robot>
